### ISSUE TITLE
Get extraction script for Labels and understand it 

### ISSUE THREAD

**Issue by Lesstat** [trump-fmi/osm_label_server#9]

**Comment by Lesstat** [comment]
Filip will write a docu on how the labels are processed.

**Comment by Mechks** [comment]
Current state as I understood: 

The labels are extracted and preprocessed with three different tools. Filip will provide a documentation of the files which are used as intermediate results. 

Work of this issue is to create a possibility to create a label file which can be configured which labels have to be extracted. This could rely on Filips tools.
